### ISSUE TITLE
Video lag in custom QGC build

### ISSUE THREAD

**Issue by karl-eaves** [CubePilot/qgroundcontrol-herelink#24]
Hello,

I cloned and modified the master branch of qgroundcontrol-herelink to add a few custom features. I have not touched any code that pertains to video streaming, etc, and have only added an extra tab in the top bar for viewing web pages. However, when I use my custom version of QGC, we experience large lag and latency from the video stream. Do you know what could be causing this lag?

This was tested on a herelink device. The following our the repository versions I am using:

Android Build Tools: 30.0.0
Android Platform: android-25
Android ABI: android-v7a
Android NDK Version: r15c
QT Version: 5.11.0
Gradle: 2.2.1

The autopilot firmware is Ardupilot.

Any help is appreciated!

**Comment by meee1** [comment]
please try 
https://github.com/CubePilot/qgroundcontrol-herelink/tree/herelink-v4.0.8

**Comment by karl-eaves** [comment]
Ahh I didn't notice the updated version tag. 

When building, I get this error: 

`clang++: error: unknown argument: '-nostdlib++'`

If I comment out the line `QMAKE_LINK += -nostdlib++ # Hack fix?: https://forum.qt.io/topic/103713/error-cannot-find-lc-qt-5-12-android` from QGCCommon.pri,  I am able to build and install the app on the updated version. However, when I run the application, it immediately crashes with the following error: 

`java.lang.UnsatisfiedLinkError: dlopen failed: library "libgnustl_shared.so" not found: needed by /data/app/~~6fwVfo7uAJKfVFB81tF3Dw==/org.mavlink.qgroundcontrol-RF-RSsopW9RJKyCJIt_D-g==/lib/arm/libQt5Core.so in namespace classloader-namespace
`

I'm not exactly sure why a Qt5 library is missing a dependency. My build setup is exactly the same as when I was building from the master branch, so I figured the Qt5 libraries should still be the same. Do I need to upgrade the QT/NDK/Build Tools for v4.0.8?
