### ISSUE TITLE
Unable to Build : error: cannot find symbol import android.os.storage.StorageVolume;

### ISSUE THREAD

**Issue by iamczar** [CubePilot/qgroundcontrol-herelink#25]
## Expected Behavior
Please tell us what should happen as detailed as possible.

## Current Behavior
unable to build due to error: cannot find symbol import android.os.storage.StorageVolume;
![image](https://user-images.githubusercontent.com/18098277/140604820-7391f462-dcb4-4c27-ba05-f235abdb5a36.png)

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. clone qgroundcontrol-herelink and open qgroundcontrol.pro with Qt creator 5.0.3
2. using /java-8-openjdk-amd64 and android-ndk-r15c

![image](https://user-images.githubusercontent.com/18098277/140604935-5965d55c-ed2a-4752-a8c0-45dd20cca383.png)

## System Information
When posting bug reports, include the following information
- Operating System: Ubuntu 20.04
- QGC Version: Current Master

## Compile Output

![image](https://user-images.githubusercontent.com/18098277/140605015-9666c77f-fa8c-4793-b667-6e7d5ec8ac86.png)

**Comment by iamczar** [comment]
Hi @DonLakeFlyer , Sorry to bother. Would you have any ideas how I could resolve this?

Should I be looking to move the repo forward to the main qgc master as a way to resolve this?

**Comment by DonLakeFlyer** [comment]
Sorry I have nothing to do with HereLink.

**Comment by iamczar** [comment]
Ah, Sorry - Did not know. But thanks for the reply

**Comment by iamczar** [comment]
Hi @bugobliterator Sid. Would you know how I could resolve it or where I can look at?

**Comment by meee1** [comment]
https://user-images.githubusercontent.com/18098277/140604935-5965d55c-ed2a-4752-a8c0-45dd20cca383.png
update your sdk version

**Comment by iamczar** [comment]
Hi @meee1 Thanks for the reply.

I was trying to build the master with Qt 5.11.0 with java-8-openjdk and ndk version 15

to which sdk version I should Update? Latest?

Also I can see that the herelink-4.0.8 is more active than master

Should I be building that instead?

**Comment by iamczar** [comment]
I tried building the herelink-4.0.8 - here is a video to give a bit of context -https://youtu.be/BFgIBO7sgM0

**Comment by iamczar** [comment]
I went to compare the herelink-4.0.8 with against the current qgc main 

I find that there was no VideoManager on the herelink...

![image](https://user-images.githubusercontent.com/18098277/141021388-70edc363-590a-42d5-8806-44ea4408f171.png)

**Comment by iamczar** [comment]
I was able to resolve this changing the version on the android manifest file
