### ISSUE TITLE
New UI - No Default Profile 

### ISSUE THREAD

**Issue by MadRC** [CubePilot/qgroundcontrol-herelink#8]
When new firmware is installed user is unable to calibrate or set joystick options, wheel setting or button options until they create a new profile on the buttons page. 

The issue with this is the profile button is the 3rd page and there is no indication to the user that they need to create a profile before they can setup on the second joystick page. 

Ideally system should install a default profile at install or prompt the user to crate a profile before configuring as it's not intuitive.

**Comment by bugobliterator** [comment]
@MadRC This is a bug, actually user shouldn't be required to create a profile before be able to calibrate. I will fix this thanks!
